# Install ruby to get gem command
before_install:
  - sudo apt-add-repository -y ppa:brightbox/ruby-ng
  - sudo apt-get -y update
  - sudo apt-get -y install ruby2.4
  - sudo apt-get -y install bash

# Install awesome_bot tool for broken link checking
before_script:
  - gem install awesome_bot

# Run broken link check
script:
    # CodeChef is white-listed as it frequently returns 504
    # Web Archive sometimes times out
    # community.topcoder.com sometimes times out
    # TOOD: Don't white-list CodeChef
    # TOOD: Don't white-list blog.anudeep2011.com (Certificate was expired)
  - awesome_bot --allow-dupe --allow-redirect --skip-save-results --white-list 'codechef.com,blog.anudeep2011.com,web.archive.org,community.topcoder.com' *.md



# Notify us if check fails
notifications:
  email:
    - suprdewd@gmail.com   # @SuprDewd
    - fisetwill@gmail.com  # @williamfiset
