name: AlgoWiki CI
on: [push]
jobs:
  broken_links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Set up awesome_bot
        run: gem install awesome_bot
      - name: Check for broken links
        # Web Archive sometimes times out
        run: awesome_bot --allow-dupe --allow-redirect --skip-save-results --white-list 'web.archive.org' wiki/*.md
